### ISSUE TITLE
Adding option for self-signed certificates

### ISSUE THREAD

**Issue by AndrevdG** [mmajcica/win-rm-file-copy#1]
A lot of the TFS/VSTS release tasks have the option to set "Test Certificate". This allows the use of self-signed certificates without validation. I have updated the task for our local use but it might be of benefit to others as well.

[win-rm-file-copy.zip](https://github.com/mmajcica/win-rm-file-copy/files/1660874/win-rm-file-copy.zip)

**Comment by mmajcica** [comment]
Hi @AndrevdG 

thank you for your feedback and I'm sorry for the late replay, somehow the notification slipped by and I just saw your message. I'll integrate your code and publish a new version.
P.S. Next time, instead of attaching a file, please make a pull request with your changes.

Thanks
