### ISSUE TITLE
Copying in parallel to multiple destination fails with test certificate

### ISSUE THREAD

**Issue by aczarkowski** [mmajcica/win-rm-file-copy#11]
We came across an issue where if copying in parallel to multiple destination fails when test certificate is ticked.
The error we got was as below
The SSL certificate is signed by an unknown certificate authority. For more information, see the about_Remote_Troubleshooting Help topic.
Only after we unticked the Copy in parallel option the copying worked.

**Comment by mmajcica** [comment]
Indeed there is a bug. I'll fix it this weekend.

**Comment by mmajcica** [comment]
@aczarkowski a new Version | 1.20.119.10 has been deployed. Can you verify that your organization received the update, that task 2.0.8 has been used in your release and obviously that the issue you reported is solved?
