### ISSUE TITLE
Exception calling "GetHostAddresses" with "1" argument(s): "No such host is known"

### ISSUE THREAD

**Issue by rfontijn** [mmajcica/win-rm-file-copy#4]
When executing version 2.0.2 of this task. The error is raised: Exception calling "GetHostAddresses" with "1" argument(s): "No such host is known"

Back to 2.0.0 everything is normal.

**Comment by mmajcica** [comment]
It should be solved in version 2.0.5
Unfortunately, in case of reverse lookup not being possible in DNS, the code in 2.0.2 would fail. Now it is fixed by simply doing only a forward lookup.

**Comment by rfontijn** [comment]
Great work. I will test it asap.

Regards,

Op vr 23 mrt. 2018 15:58 schreef Mario Majcica <notifications@github.com>:

**Comment by mmajcica** [comment]
@rfontijn thanks!

**Comment by rerime** [comment]
Same problem in 2.0.6 with function Resolve-HostNameOrAddress
```
[System.Net.Dns]::GetHostEntry("10.0.0.1")
Exception calling "GetHostEntry" with "1" argument(s): "No such host is known"
At line:1 char:1
+ [System.Net.Dns]::GetHostEntry("10.0.0.1")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SocketException
```

**Comment by mmajcica** [comment]
Hi @rerime ,

I do not see this being an issue. Can you provide some more information?

If I run the following on one of my machines:

```
PS H:\> ([System.Net.Dns]::GetHostEntry("10.193.151.58")).HostName

nlwpr-bi4621-dtap-lb-md1-70-vip48.nvd.itb.intranet
```

DNS name of the host is resolved correctly.

Is that your host entry can't be resolved?

Aside of this, I was thinking of getting rid of it completely and imply the machine name or ipaddress as for all other standard MS tasks. I introduced that because I was trying to reach one of my servers via CNAME entry, but since the day one it just gave issues.

**Comment by rerime** [comment]
@mmajcica 
You can try my example. 
`[System.Net.Dns]::GetHostEntry("10.0.0.1")`
It is possible in networks that can be routed, but without records in dns. 

If $ComputerName is IP address, why you try to connect by dns name?
```
 if ([bool]($ComputerName -as [ipaddress]))
        {
            $host1 = [System.Net.Dns]::GetHostEntry($ComputerName)
        }
        else
        {
            $host1 = [System.Net.Dns]::GetHostByName($ComputerName)
        }

        return $host1.HostName
```
With your current realization you convert IP to DNS, then try to connect. It fails if PTR doesn't exist.

**Comment by mmajcica** [comment]
@rerime 

You are right, I'll take care of this issue later in the day. Expect to have a new version of the task ready for tomorrow.

**Comment by rerime** [comment]
@mmajcica 
I created pull request)

**Comment by rerime** [comment]
@mmajcica 
I further thinking about possible problem... if it resolves PTR and then connect to dns, it is possible that you connect to another IP address for records that has multiple records. Example, 9.9.9.9
```
HostName      Aliases AddressList               
--------      ------- -----------               
dns.quad9.net {}      {149.112.112.112, 9.9.9.9}
```
I guess better just return IP address like in my first pull request.

**Comment by mmajcica** [comment]
@rerime I'm not an expert on the matter, What you are suggesting sounds valid, but I have no chance to test it. I'll trust you on this one. Can you make another PR and also bump up the task version and try it?

**Comment by mmajcica** [comment]
Also MS task originally support only a IP address or FQDN:

https://github.com/Microsoft/vsts-tasks/blob/e5420d66ee4e6bcd3eeabbc0e6a336fbb70f67cc/Tasks/WindowsMachineFileCopyV2/task.json#L42

And it doesn't perform any check or resolution on it. If then mounting the New-PSDrive succeeds (and it's verification over the provided name succeeds)

https://github.com/Microsoft/vsts-tasks/blob/e5420d66ee4e6bcd3eeabbc0e6a336fbb70f67cc/Tasks/WindowsMachineFileCopyV2/RoboCopyJob.ps1#L173

For him it is all good.

So I would be keen to get rid of all of this name resolution.

**Comment by mmajcica** [comment]
@rerime Done, the new version is on the Marketplace. 

Thank you for your contribution.
