### ISSUE TITLE
Does not work in TFS 2015 

### ISSUE THREAD

**Issue by fabiostawinski** [mmajcica/win-rm-file-copy#5]
Hello, I have added the extension to a TFS 2015 and the build step was not available. I tested in TFS 2017 then it worked.

**Comment by mmajcica** [comment]
Hi @fabiostawinski 

I'm sorry to hear that.  This task should be compatible with TFS 2015.2 upwards. For some strange reason that I still need to check, minimum agent version is set to 1.104.0. It should be however able to run on agent version 1.95.1. I'll make some test tomorrow and come back to you.

**Comment by fabiostawinski** [comment]
@mmajcica yes, that is exactly the error in the logs... thanks for that

**Comment by mmajcica** [comment]
@fabiostawinski I went through the task and there is no reason why the minimumAgentVersion should not be set to 1.95.0 and be compatible with TFS 2015.2. I released a new pre-release with that change and you can find it here https://github.com/mmajcica/win-rm-file-copy/releases/tag/1.0.7
Would you be so kind and give it a spin before I publish it to the marketplace (as I have no TFS 2015 instances to try it on).

Thanks

**Comment by fabiostawinski** [comment]
@mmajcica done, it works! Awesome, thanks.

**Comment by mmajcica** [comment]
Perfect, I'll publish the new version on the marketplace this evening.
