### ISSUE TITLE
Do not copy parent folder

### ISSUE THREAD

**Issue by rerime** [mmajcica/win-rm-file-copy#6]
When copy from '$(System.ArtifactsDirectory)\Something', how to skip folder something?

**Comment by mmajcica** [comment]
Can you describe me a bit better your case? What is the status of source folders, what are you trying to achieve?

**Comment by rerime** [comment]
I know this bug https://stackoverflow.com/questions/5926346/copy-folder-using-copy-item-different-behaviour

**Comment by rerime** [comment]
Copy-Item -Path C:\temp1 -Destination c:\temp2 -Force -Recurse -Container
In C:\temp1\ (1.zip, 2.zip) multiple zip files, I want to c:\temp2\1.zip etc

Need a behavior like 
https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/windows-machine-file-copy?view=vsts

**Comment by mmajcica** [comment]
First of all, thank you for your effort. You can now see through how much of pain I went in trying to mimic the same behaviour as the original task has and that is based on xcopy.
Said that, what you are suggesting it should already be the case, check the following code:

```
if(-not (Test-Path -LiteralPath $sourcePath))
    {
        throw "Source path '$sourcePath' does not exist."
    }
    else
    {
        $path = Get-Item $sourcePath
        
        if ($path -is [System.IO.DirectoryInfo] -and (-not ($sourcePath.EndsWith("\"))))
        {
            $sourcePath += "\*"
        }
    }
```

Thus it means there is no need for it to be later as in your change, `Copy-Item -Path $sourcePath\* `.
If this is not the case, let's check why and fix the validation before we execute the command.
Can you launch a build/release with high verbosity and post the logs?

**Comment by rerime** [comment]
Didn't noticed that) Confirmed, it is fixed my issue (delete tail slash).
